FROM bitnami/postgresql:15

LABEL name "postgres_slave_db_for_replication_cluster"
LABEL maitainer_mail arrian8@yandex.ruF

ENV POSTGRESQL_REPLICATION_MODE slave
ENV POSTGRESQL_USER user
ENV POSTGRESQL_PASSWORD qwerty
ENV ALLOW_EMPTY_PASSWORD yes
